import Head from "next/head";
import Image from "next/image";
import {
  Box,
  Code,
  Container,
  Flex,
  Heading,
  Link,
  Text
} from "@chakra-ui/react";
// import styles from "../styles/Home.module.css";

// @NOTE:

const cardStyles = {
  margin: 4, // preset for '1rem'
  padding: 6, // preset for '1.5rem'
  textAlign: "left",
  color: "inherit",
  textDecoration: "none",
  border: "1px solid",
  borderColor: "brand.50",
  borderRadius: "10px",
  transition: "color 0.15s ease, border-color 0.15s ease",
  maxWidth: "300px",
  _hover: {
    color: "brand.200",
    borderColor: "brand.200"
  },
  _focus: {
    color: "brand.200",
    borderColor: "brand.200"
  },
  _active: {
    color: "brand.200",
    borderColor: "brand.200"
  },
  h2: {
    marginBottom: 4, // preset for '1rem'
    fontSize: "2xl" // preset for '1.5rem'
  },
  p: {
    m: 0,
    fontSize: "xl",
    lineHeight: "base"
  }
};

export default function Home() {
  return (
    <Container px={0} py={10} maxW="container.md">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading as="h1" textStyle="title">
          Welcome to{" "}
          <Link color="brand.200" href="https://nextjs.org" isExternal>
            Next.js!
          </Link>
        </Heading>

        <Text textStyle="description">
          Get started by editing <Code>pages/index.js</Code>
        </Text>

        <Flex
          w="full"
          flexDir={["column", "row"]}
          align="center"
          justifyContent="center"
          wrap="wrap"
        >
          <Link href="https://nextjs.org/docs" isExternal {...cardStyles}>
            <Heading as="h2" {...cardStyles.h2}>
              Documentation &rarr;
            </Heading>
            <Text {...cardStyles.p}>
              Find in-depth information about Next.js features and API.
            </Text>
          </Link>

          <Link href="https://nextjs.org/learn" isExternal {...cardStyles}>
            <Heading as="h2" {...cardStyles.h2}>
              Learn &rarr;
            </Heading>
            <Text {...cardStyles.p}>
              Learn about Next.js in an interactive course with quizzes!
            </Text>
          </Link>

          <Link
            href="https://github.com/vercel/next.js/tree/master/examples"
            isExternal
            {...cardStyles}
          >
            <Heading as="h2" {...cardStyles.h2}>
              Examples &rarr;
            </Heading>
            <Text {...cardStyles.p}>
              Discover and deploy boilerplate example Next.js projects.
            </Text>
          </Link>

          <Link
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            {...cardStyles}
          >
            <Heading as="h2" {...cardStyles.h2}>
              Deploy &rarr;
            </Heading>
            <Text {...cardStyles.p}>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </Text>
          </Link>
        </Flex>
      </main>

      <footer>
        <Flex
          as={Link}
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          isExternal
          justify="center"
          align="center"
          flex="1"
        >
          Powered by{" "}
          <Box as="span" h="1em" ml={2}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </Box>
        </Flex>
      </footer>
    </Container>
  );
}
